source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
project 'DMAELASDKTEST'

inhibit_all_warnings!
use_frameworks!

target 'DMAELASDKTEST' do
   pod 'HandyJSON', '~> 5.0.0' 
   pod 'Alamofire', '~> 4.7'
   pod 'starrymediaDMA-Util'
end

